In [10]:
from funciones import f1
import common
from metodos import realizar_metodo, metodo_euler, runge_kutta4
import numpy as np
import math

y= np.float(math.radians(30))
u= np.float(math.radians(100)) # cambiar a 0 para sin amortiguado


paso = 0.02 # cambiar el paso para probar casos
rango_maximo = 20
valores_euler = realizar_metodo(metodo_euler,f1, 0, rango_maximo, y, u, paso)
valores_rk4 = realizar_metodo(runge_kutta4,f1, 0, rango_maximo, y, u, paso)

#common.crear_grafico(valores_euler, valores_rk4)
#common.crear_grafico_overlap(valores_euler, valores_rk4)
df_euler, df_rk4 = common.crear_tablas(valores_euler, valores_rk4)

In [11]:
df_euler

   tiempo  posicion  velocidad
0    0.00  0.523599   0.000000
1    0.02  0.523599  -0.102730
2    0.04  0.521544  -0.205460
3    0.06  0.517435  -0.307787
4    0.08  0.511279  -0.409308
5   19.92  3.191146   5.749275
6   19.94  3.306131   5.123172
7   19.96  3.408595   4.474509
8   19.98  3.498085   3.805743
9   20.00  3.574200   3.119419

In [12]:
df_rk4

   tiempo  posicion  velocidad
0    0.00  0.523599   0.000000
1    0.02  0.522572  -0.102680
2    0.04  0.519495  -0.204990
3    0.06  0.514379  -0.306530
4    0.08  0.507243  -0.406900
5   19.92  0.556541   0.832255
6   19.94  0.572083   0.721755
7   19.96  0.585387   0.608387
8   19.98  0.596399   0.492596
9   20.00  0.605074   0.374835